[package]
name = "file-channel"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.31", default-features = false }
pin-project = "1.1.7"
tokio = { version = "1.42.0", features = ["rt"] }

[dev-dependencies]
tempfile = "3.14.0"
tokio = { version = "1.42.0", features = ["macros"] }
