[package]
name = "file-channel"
version = "0.1.0"
edition = "2021"

[features]
default = ["futures-io", "tokio-rt"]
futures-io = ["futures/std"]
tokio-rt = ["tokio/rt"]

[dependencies]
futures = { version = "0.3.31", default-features = false }
libc = "0.2.169"
pin-project = "1.1.7"
slab = "0.4.9"
tokio = { version = "1.42.0", optional = true }

[dev-dependencies]
rand = "0.8.5"
tempfile = "3.14.0"
tokio = { version = "1.42.0", features = ["macros"] }
